name: flutter_app_host
description: Quickly distribute your Flutter app to testers or enterprise users by uploading it to the AppHost hosting service
version: 0.1.0
author: AppHost
homepage: https://github.com/apphost-plugins/flutter_app_host

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  path: "^1.6.2"
  http: "^0.12.0+2"
